// Phase 3: turn tools/desmos/mapping.json into upsert SQL for the main D1 database.
//   node tools/desmos/import.cjs [--bank <file> | --local] [--in mapping.json] [--out file.sql]
//   then (by hand):  npx wrangler d1 execute DB --remote --file=tools/desmos/desmos_solutions.sql
//
// Like tools/apply_ai.cjs, every row is validated first and one bad row refuses the whole run, so a
// partial file never ships. A row is refused when its question_id is not a core question in the bank
// (AI questions have no Prepzy solutions, and desmos_solutions lives in the main DB only), when its
// state is not a loadable Desmos state, or when its statement would exceed D1's statement size.
//
// The SQL is idempotent: an upsert keyed on question_id that writes nothing when the stored row
// already holds the same state, credit and fingerprint (no row-write budget spent on a rerun). Each
// INSERT also re-checks `EXISTS (SELECT 1 FROM questions WHERE id = ...)` on the database it runs
// against, so an ID missing from the remote bank is skipped there rather than inserted.
// Migration 0015 must already be applied to that database.
const fs = require('fs');
const path = require('path');
const { DIR, loadBank, stateProblems } = require('./common.cjs');

// D1 refuses a single statement over 100 KB; keep clear of it.
const MAX_STATEMENT = 90000;
const MAX_CREDIT = 100;
const MAX_FINGERPRINT = 200;
const ID = /^[A-Za-z0-9_-]{1,64}$/;

const CTRL = /[\x00-\x08\x0b\x0c\x0e-\x1f]/g;
const lit = (v) => v === null || v === undefined ? 'NULL' : "'" + String(v).replace(CTRL, '').replace(/'/g, "''") + "'";

function statement(r) {
  const state = JSON.stringify(r.state);
  const id = lit(r.question_id);
  return `INSERT INTO desmos_solutions (question_id, state_json, credit_name, source, source_fingerprint, imported_at)` +
    ` SELECT ${id}, ${lit(state)}, ${lit(r.credit_name)}, 'prepzy', ${lit(r.source_fingerprint)}, datetime('now')` +
    ` WHERE EXISTS (SELECT 1 FROM questions WHERE id = ${id})` +
    ` ON CONFLICT(question_id) DO UPDATE SET state_json=excluded.state_json, credit_name=excluded.credit_name,` +
    ` source=excluded.source, source_fingerprint=excluded.source_fingerprint, imported_at=excluded.imported_at` +
    ` WHERE desmos_solutions.state_json IS NOT excluded.state_json OR desmos_solutions.credit_name IS NOT excluded.credit_name` +
    ` OR desmos_solutions.source IS NOT excluded.source OR desmos_solutions.source_fingerprint IS NOT excluded.source_fingerprint;`;
}

// Every reason the mapping must not ship; empty means it is safe to emit.
function problems(mapping, coreIds) {
  const bad = [], seen = new Set();
  if (!Array.isArray(mapping)) return ['mapping.json is not an array'];
  mapping.forEach((r, i) => {
    const at = `row ${i} (${r && r.question_id})`;
    if (!r || typeof r !== 'object') return bad.push(`${at}: not an object`);
    if (typeof r.question_id !== 'string' || !ID.test(r.question_id)) return bad.push(`${at}: invalid question_id`);
    if (seen.has(r.question_id)) bad.push(`${at}: duplicate question_id`);
    seen.add(r.question_id);
    if (!coreIds.has(r.question_id)) bad.push(`${at}: unknown question_id (not in the core questions table)`);
    for (const p of stateProblems(r.state)) bad.push(`${at}: ${p}`);
    if (r.credit_name != null && (typeof r.credit_name !== 'string' || r.credit_name.length > MAX_CREDIT)) bad.push(`${at}: credit_name is not a string of at most ${MAX_CREDIT} characters`);
    if (typeof r.credit_name === 'string' && /@/.test(r.credit_name)) bad.push(`${at}: credit_name looks like an email address`);
    if (r.source_fingerprint != null && (typeof r.source_fingerprint !== 'string' || r.source_fingerprint.length > MAX_FINGERPRINT)) bad.push(`${at}: source_fingerprint too long`);
    if (!bad.some(b => b.startsWith(at)) && statement(r).length > MAX_STATEMENT) bad.push(`${at}: state is too large for one D1 statement`);
  });
  return bad;
}

// The whole file, rows in question_id order so a rerun on the same mapping produces the same bytes.
function buildSql(mapping, coreIds) {
  const bad = problems(mapping, coreIds);
  if (bad.length) { const e = new Error(`REFUSED - ${bad.length} problem(s):\n${bad.join('\n')}`); e.problems = bad; throw e; }
  const rows = [...mapping].sort((a, b) => a.question_id.localeCompare(b.question_id));
  return `-- Generated by tools/desmos/import.cjs from tools/desmos/mapping.json (${rows.length} rows). Do not hand-edit.\n` +
    '-- Needs migrations/0015_desmos_solutions.sql. Idempotent: safe to run again.\n' +
    rows.map(statement).join('\n') + '\n';
}

function main() {
  const arg = (k, d) => { const i = process.argv.indexOf(k); return i >= 0 ? process.argv[i + 1] : d; };
  const file = arg('--in', path.join(DIR, 'mapping.json'));
  const out = arg('--out', path.join(DIR, 'desmos_solutions.sql'));
  const mapping = JSON.parse(fs.readFileSync(file, 'utf8'));
  const coreIds = new Set(loadBank(process.argv).filter(q => q.bank === 'core').map(q => q.id));
  try { fs.writeFileSync(out, buildSql(mapping, coreIds)); }
  catch (e) { console.error(e.message); process.exit(1); }
  console.log(`${mapping.length} row(s) validated; ${path.relative(process.cwd(), out)} written. Not applied: run it with wrangler d1 execute DB.`);
}

if (require.main === module) main();
module.exports = { buildSql, problems, statement, MAX_STATEMENT };
