import { test, expect } from '@playwright/test';
import { newUserContext, ORIGIN } from '../lessons-00b-e2e-harness/auth.js';

const artifacts = '.opencode/pipeline/ui-student-player/e2e';

test('Bluebook student island states, private marks, stable body and light theme', async ({ browser }) => {
  const admin = await newUserContext(browser, 'e2e-admin', { viewport: { width:1920, height:1080 } });
  const context = await newUserContext(browser, 'e2e-student-4', { colorScheme:'dark' });
  try {
    const created = await admin.request.post('/api/admin/lessons', { headers:{ Origin:ORIGIN }, data:{ title:'SAT Club · Live practice', mode:'instructor', items:[{ question_id:'e2e-ai-rw', time_limit_sec:90, notes:'' }, { question_id:'e2e-core-math', time_limit_sec:90, notes:'' }] } });
    expect(created.status()).toBe(200);
    const lesson = await created.json();
    const started = await admin.request.post(`/api/admin/lessons/${lesson.id}/sessions`, { headers:{ Origin:ORIGIN } });
    expect(started.status()).toBe(200);
    const { sessionId, joinCode } = await started.json();
    const teacher = await admin.newPage(); await teacher.goto(`/admin/live/${sessionId}`);
    await expect(teacher.locator('#live-link')).toHaveText('Connected');
    let upstream;
    await context.routeWebSocket(/\/api\/lessons\/\d+\/ws/, route => { upstream = route.connectToServer(); });
    const page = await context.newPage();
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    await page.goto(`/app?join=${joinCode}`);
    await expect(page.locator('#lesson-content')).toContainText('Waiting for the instructor to start…');
    await expect(page.locator('#lesson-live')).toHaveCSS('color-scheme','light');
    await expect(page.locator('#lesson-live')).toHaveCSS('background-color','rgb(255, 255, 255)');
    await expect(page.locator('#lesson-connection')).toHaveText('Connected');
    const screenshot = name => page.screenshot({ path:`${artifacts}/${name}.png` });
    await screenshot('01-lobby');
    await teacher.locator('[data-live="start"]').click();
    await expect(page.locator('#lesson-card')).toHaveAttribute('data-ready','true');
    await expect(page.locator('[data-lesson-choice="B"]')).toBeEnabled();
    await screenshot('02-answering-rw');
    await page.evaluate(() => { window.__originalLessonBody = document.querySelector('#lesson-card .lesson-stem'); });
    await page.locator('#lesson-private').click();
    await page.locator('#lesson-card .lesson-stem p').evaluate(el => {
      const range = document.createRange(); range.setStart(el.firstChild,0); range.setEnd(el.firstChild,5);
      const selection = window.getSelection(); selection.removeAllRanges(); selection.addRange(range);
      el.dispatchEvent(new PointerEvent('pointerup',{ bubbles:true }));
    });
    await expect(page.locator('#lesson-card [data-ann-mark]')).toHaveText('Which');
    await page.locator('[data-lesson-choice="B"]').click();
    await expect(page.locator('[data-lesson-choice="B"]')).toHaveAttribute('aria-pressed','true');
    expect(await page.evaluate(() => window.__originalLessonBody === document.querySelector('#lesson-card .lesson-stem'))).toBe(true);
    await screenshot('03-selected');
    await page.locator('#lesson-lock').click();
    await expect(page.getByRole('dialog')).toBeVisible();
    await screenshot('04-confirm');
    await page.locator('#lesson-confirm').click();
    await expect(page.locator('#lesson-content')).toContainText('Answer locked in. Waiting for time to end…');
    await expect(page.locator('#lesson-content')).not.toContainText('Correct answer:');
    await screenshot('05-locked');
    await teacher.locator('[data-live="endNow"]').click();
    await expect(page.locator('[data-lesson-choice="A"] .choice')).toHaveClass(/right/);
    await expect(page.locator('[data-lesson-choice="B"] .choice')).toHaveClass(/wrong/);
    await expect(page.locator('[data-lesson-choice="A"] svg')).toBeVisible();
    await expect(page.locator('#lesson-card [data-ann-mark]')).toHaveText('Which');
    await teacher.locator('#live-responses').click();
    await teacher.locator('#live-class').check();
    await expect(page.locator('.lesson-results')).toBeVisible();
    await screenshot('06-revealed');
    await page.locator('.lesson-more summary').click();
    await page.locator('#lesson-private-clear').click();
    await expect(page.locator('#lesson-card [data-ann-mark]')).toHaveCount(0);
    await page.locator('.lesson-more summary').click();
    await teacher.locator('[data-live="next"]').click();
    await teacher.locator('[data-live="startQuestion"]').click();
    await expect(page.locator('#lesson-card')).toHaveAttribute('data-ready','true');
    await expect(page.locator('#lesson-card .katex')).toBeVisible();
    await expect(page.locator('#lesson-card')).toHaveClass(/stage-math/);
    await screenshot('07-answering-math');
    await page.getByRole('button',{ name:'Hide timer' }).click();
    await expect(page.locator('#lesson-clock')).toHaveCSS('visibility','hidden');
    await page.getByRole('button',{ name:'Show timer' }).click();
    const disconnected = page.waitForEvent('websocket', { predicate: ws => ws.url().includes('/api/lessons/') });
    await upstream.close({ code:1000, reason:'offline test' });
    await context.setOffline(true);
    await expect(page.locator('.lesson-reconnect')).toHaveText('Reconnecting…');
    await screenshot('08-reconnecting');
    await context.setOffline(false);
    await disconnected;
    await expect(page.locator('#lesson-connection')).toHaveText('Connected');
    expect(errors).toEqual([]);
  } finally { await context.close(); await admin.close(); }
});
