-- Rotated axis titles and figure labels left out of the figure crop came out as stray glyph rows under it.
-- The figure crops (public/qimg/<id>_fig0.webp) were replaced with complete figures; these UPDATEs remove the stray rows.
UPDATE questions SET stem_html='<h3>Passage</h3><div class="qfig"><img src="/qimg/0013adbd_fig0.webp" alt="Figure"></div><h3>Prompt</h3><p>In the figure, line \(t\) intersects lines \(j\) and \(k\). Which additional piece of information is sufficient to prove that lines \(j\) and \(k\) are parallel?</p>' WHERE id='0013adbd';
UPDATE questions SET stem_html='<h3>Passage</h3><p>The graph shown models the number of candy bars a certain machine wraps with a label in \(x\) seconds.</p><div class="qfig"><img src="/qimg/13294295_fig0.webp" alt="Figure"></div><h3>Prompt</h3><p>According to the graph, what is the estimated number of candy bars the machine wraps with a label per second?</p>' WHERE id='13294295';
UPDATE questions SET stem_html='<h3>Passage</h3><div class="qfig"><img src="/qimg/197bed38_fig0.webp" alt="Figure"></div><h3>Prompt</h3><p>An object was launched upward from a platform. The graph shown models the height above ground, \(y\), in meters, of the object \(x\) seconds after it was launched. For which of the following intervals of time was the height of the object increasing for the entire interval?</p>' WHERE id='197bed38';
UPDATE questions SET stem_html='<h3>Passage</h3><div class="qfig"><img src="/qimg/1a1a95de_fig0.webp" alt="Figure"></div><h3>Prompt</h3><p>A certain open star cluster contains M-type stars and K-type stars. The estimated total mass of M-type and K-type stars in this open star cluster is \(127,882\text{ quettagrams}\). The graph shown models the possible combinations of the number of M-type stars, \(x\), and K-type stars, \(y\), that could be in this open star cluster if all the M-type stars have the same estimated mass and all the K-type stars have the same estimated mass. Based on the graph, which of the following is closest to the estimated mass, in quettagrams, of each M-type star in this cluster?</p>' WHERE id='1a1a95de';
UPDATE questions SET stem_html='<h3>Passage</h3><div class="qfig"><img src="/qimg/2e0290c3_fig0.webp" alt="Figure"></div><h3>Prompt</h3><p>The graph shows the relationship between the number of shares of stock from Company A, \(x\), and the number of shares of stock from Company B, \(y\), that Simone can purchase. Which equation could represent this relationship?</p>' WHERE id='2e0290c3';
UPDATE questions SET stem_html='<h3>Passage</h3><div class="qfig"><img src="/qimg/2ecce641_fig0.webp" alt="Figure"></div><h3>Prompt</h3><p>A bank account was opened with an initial deposit. Over the next several months, regular deposits were made into this account, and there were no withdrawals made during this time. The graph of the function \(f\) shown, where \(y= f(x)\), estimates the account balance, in dollars, in this bank account \(x\) months since the initial deposit. To the nearest whole dollar, what is the amount of the initial deposit estimated by the graph?</p>' WHERE id='2ecce641';
UPDATE questions SET stem_html='<h3>Passage</h3><div class="qfig"><img src="/qimg/3b44439b_fig0.webp" alt="Figure"></div><h3>Prompt</h3><p>In the figure, line \(p\) is parallel to line \(q\), and line \(t\) intersects both lines. What is the value of \(x + 142\)?</p>' WHERE id='3b44439b';
UPDATE questions SET stem_html='<h3>Passage</h3><div class="qfig"><img src="/qimg/4fbffc0a_fig0.webp" alt="Figure"></div><h3>Prompt</h3><p>The graph shows the height above ground, in meters, of a ball \(x\) seconds after the ball was launched upward from a platform. Which statement is the best interpretation of the marked point (1.0,4.8) in this context?</p>' WHERE id='4fbffc0a';
UPDATE questions SET stem_html='<h3>Passage</h3><p>The scatterplot shows the relationship between the length of time \(y\), in hours, a certain bird spent in flight and the number of days after January 11, \(x\).</p><div class="qfig"><img src="/qimg/7b52985c_fig0.webp" alt="Figure"></div><h3>Prompt</h3><p>What is the average rate of change, in hours per day, of the length of time the bird spent in flight on January 13 to the length of time the bird spent in flight on January 15?</p>' WHERE id='7b52985c';
UPDATE questions SET stem_html='<h3>Passage</h3><div class="qfig"><img src="/qimg/8368afd1_fig0.webp" alt="Figure"></div><h3>Prompt</h3><p>The graph shows the possible combinations of the number of pounds of tangerines and lemons that could be purchased for $18 at a certain store. If Melvin purchased lemons and 4 pounds of tangerines for a total of $18, how many pounds of lemons did he purchase?</p>' WHERE id='8368afd1';
UPDATE questions SET stem_html='<h3>Passage</h3><p>The scatterplot shows the relationship between the weight, in pounds, of each of 9 female gray wolves on April 30 and the number of offspring each gray wolf produced.</p><div class="qfig"><img src="/qimg/8d63b6f1_fig0.webp" alt="Figure"></div><h3>Prompt</h3><p>How many offspring did the 50-pound gray wolf produce?</p>' WHERE id='8d63b6f1';
UPDATE questions SET stem_html='<h3>Passage</h3><p>Hydrogen is placed inside a container and kept at a constant pressure. The graph shows the estimated volume \(y\), in liters, of the hydrogen when its temperature is \(x\) kelvins.</p><div class="qfig"><img src="/qimg/930c2990_fig0.webp" alt="Figure"></div><h3>Prompt</h3><p>What is the estimated volume, in liters, of the hydrogen when its temperature is 500 kelvins?</p>' WHERE id='930c2990';
UPDATE questions SET stem_html='<h3>Passage</h3><div class="qfig"><img src="/qimg/9bb4107c_fig0.webp" alt="Figure"></div><h3>Prompt</h3><p>The graph shows the momentum \(y\), in newton-seconds, of an object \(x\) seconds after the object started moving, for \(0 \le x \le 8\). What is the average rate of change, in newton-seconds per second, in the momentum of the object from \(x = 2\) to \(x = 6\)?</p>' WHERE id='9bb4107c';
UPDATE questions SET stem_html='<h3>Passage</h3><div class="qfig"><img src="/qimg/9ff88bb5_fig0.webp" alt="Figure"></div><h3>Prompt</h3><p>A competitive diver dives from a platform into the water. The graph shown gives the height above the water \(y\), in meters, of the diver \(x\) seconds after diving from the platform. What is the best interpretation of the x-intercept of the graph?</p>' WHERE id='9ff88bb5';
UPDATE questions SET stem_html='<h3>Passage</h3><div class="qfig"><img src="/qimg/babd7461_fig0.webp" alt="Figure"></div><h3>Prompt</h3><p>In the figure shown, triangle \(JKL\) is similar to triangle \(RST\), where \(J\) corresponds to \(R\) and \(K\) corresponds to \(S\). The length of \(JK\) is 15, and the perimeter of triangle \(JKL\) is 36. The length of \(RS\) is 135. What is the perimeter of triangle \(RST\)?</p>' WHERE id='babd7461';
UPDATE questions SET stem_html='<h3>Passage</h3><p>Argon is placed inside a container with a constant volume. The graph shows the estimated pressure \(y\), in pounds per square inch (psi), of the argon when its temperature is \(x\) kelvins.</p><div class="qfig"><img src="/qimg/d0cb49e8_fig0.webp" alt="Figure"></div><h3>Prompt</h3><p>What is the estimated pressure of the argon, in \(psi\), when the temperature is 600 kelvins?</p>' WHERE id='d0cb49e8';
UPDATE questions SET stem_html='<h3>Passage</h3><p>The scatterplot shows the temperature \(y\), in \(^{\circ}F\), recorded by a meteorologist at various times \(x\), in days since June 1.</p><div class="qfig"><img src="/qimg/d112bc9d_fig0.webp" alt="Figure"></div><h3>Prompt</h3><p>During which of the following time periods did the greatest increase in recorded temperature take place?</p>' WHERE id='d112bc9d';
UPDATE questions SET stem_html='<h3>Passage</h3><div class="qfig"><img src="/qimg/d94018fd_fig0.webp" alt="Figure"></div><h3>Prompt</h3><p>Each of the dot plots shown represents the number of glue sticks brought in by each student for two classes, class A and class B. Which statement best compares the standard deviations of the numbers of glue sticks brought in by each student for these two classes?</p>' WHERE id='d94018fd';
